-- MODIFICO LA VARIABLE DEL SISTEMA

alter session set "_ORACLE_SCRIPT"=true;

-- CREACION TABLESPACE 'EMPRESA'

CREATE TABLESPACE EMPRESA
DATAFILE 'empresa.dbf'
SIZE 400M
AUTOEXTEND ON;

-- CONSULTO LA VISTA DE LOS TABLESPACE PARA CONFIRMAR SU CREACION

SELECT * FROM DBA_TABLESPACES;

-- CREACION USUARIO 'TECNICO' CON TODOS LOS PRIVILEGIOS EN EL SISTEMA ORACLE

CREATE USER TECNICO IDENTIFIED BY "TECNICO"
DEFAULT TABLESPACE EMPRESA
QUOTA UNLIMITED ON EMPRESA;
GRANT CREATE SESSION TO TECNICO;


GRANT DBA TO TECNICO;

SELECT * FROM DBA_SYS_PRIVS 
WHERE GRANTEE = 'TECNICO';



-- CREACION TABLA 'INCIDENCIAS'

CREATE TABLE INCIDENCIAS (
    COD_INC NUMBER PRIMARY KEY NOT NULL,
    EQUIPO NUMBER NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(500),
    USUARIO NUMBER UNIQUE,
    FECHA_HORA TIMESTAMP,
    SOLUCIONADO CHAR(1),
    COSTE FLOAT
) TABLESPACE EMPRESA;


SELECT * FROM INCIDENCIAS;

-- INSERTO DATOS EN LA TABLA

INSERT INTO INCIDENCIAS VALUES (01, 33, 'COMPONENTE DAÑADO', 01, CURRENT_TIMESTAMP, 'S', 100);
INSERT INTO INCIDENCIAS VALUES (02, 34, 'PLACA BASE QUEMADA', 02, CURRENT_TIMESTAMP, 'N', 500);
INSERT INTO INCIDENCIAS VALUES (03, 01, 'COMPONENTE DAÑADO', 03, CURRENT_TIMESTAMP, 'S', 150);
INSERT INTO INCIDENCIAS VALUES (04, 03, 'VENTILADORES QUEMADA', 04, CURRENT_TIMESTAMP, 'S', 300);
INSERT INTO INCIDENCIAS VALUES (05, 13, 'COMPONENTE DAÑADO', 05, CURRENT_TIMESTAMP, 'S', 100);
INSERT INTO INCIDENCIAS VALUES (06, 54, 'PANTALLA DAÑADA', 06, CURRENT_TIMESTAMP, 'N', 300);
INSERT INTO INCIDENCIAS VALUES (07, 99, 'COMPONENTE DAÑADO', 07, CURRENT_TIMESTAMP, 'S', 150);
INSERT INTO INCIDENCIAS VALUES (08, 07, 'VENTILADORES QUEMADA', 08, CURRENT_TIMESTAMP, 'S', 300);


-- COMPRUEBO A QUIEN PERTENECE LA TABLA INCIDENCIAS

SELECT *FROM ALL_TABLES
WHERE TABLE_NAME = 'INCIDENCIAS';

-- CREO LOS USUARIOS 'USER1' Y 'USER2' CON PASSWORD 'ABCD1234' QUE SE ENCARGEN DE LA GESTION
-- (AÑADIR, MODIFICAR, BORRAR, CONSULTAR)

CREATE USER USER1 IDENTIFIED BY "ABCD1234"
DEFAULT TABLESPACE EMPRESA
QUOTA UNLIMITED ON EMPRESA;
GRANT CREATE SESSION TO USER1; 

CREATE USER USER2 IDENTIFIED BY "ABCD1234"
DEFAULT TABLESPACE EMPRESA
QUOTA UNLIMITED ON EMPRESA;
GRANT CREATE SESSION TO USER2;

-- COMPRUEBO QUE SE HAN CREADO

SELECT * FROM DBA_USERS ORDER BY USERNAME;
    
-- ASIGNO PRIVILEGIOS PARA AÑADIR, MODIFICAR, BORRAR, CONSULTAR

GRANT UPDATE, INSERT, DELETE, SELECT 
      ON TECNICO.INCIDENCIAS
      TO USER1, USER2;

-- COMPRUEBO LOS PRIVILEGIOS ASIGNADOS SOBRE EL SISTEMA

SELECT * FROM DBA_SYS_PRIVS 
WHERE GRANTEE = 'USER1' OR GRANTEE = 'USER2';

-- COMPRUEBO LOS PRIVILEGIOS ASIGNADOS SOBRE LA TABLA INCIDENCIAS

SELECT * FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'USER1' OR GRANTEE = 'USER2'
ORDER BY GRANTEE;

-- COMPRUEBO LOS PRIVILEGIOS CON USER1

SELECT * FROM TECNICO.INCIDENCIAS;
INSERT INTO TECNICO.INCIDENCIAS VALUES (09, 08, 'MEMORIA RAM', 09, CURRENT_TIMESTAMP, 'S', 600);
UPDATE TECNICO.INCIDENCIAS SET COSTE = 1000 WHERE USUARIO = 3;
DELETE FROM TECNICO.INCIDENCIAS WHERE COD_INC = 09;

-- COMPRUEBO LOS PRIVILEGIOS CON USER2

SELECT * FROM TECNICO.INCIDENCIAS;
INSERT INTO TECNICO.INCIDENCIAS VALUES (10, 13, 'PROCESADOR', 13, CURRENT_TIMESTAMP, 'N', 2000);
UPDATE TECNICO.INCIDENCIAS SET SOLUCIONADO = 'S' WHERE USUARIO = 2;
DELETE FROM TECNICO.INCIDENCIAS WHERE COD_INC = 10;

-- USER1 RECIBE EL PRIVILEGIO DE CREAR USUARIOS, PERO NO PODRA ELIMINAR NINGUNO
-- EL PRIVILEGIO DE ELIMINAR USUARIOS NO SE LO PUEDO QUITAR PORQUE USER1 NO POSEE TAL PRIVILEGIO

GRANT CREATE USER TO USER1;

-- COMPRUEBO QUE LO TIENE ASGINADO

SELECT * FROM DBA_SYS_PRIVS 
WHERE GRANTEE = 'USER1';

-- QUITO EL PRIVILEGIO DE BORRAR A USER2

REVOKE DELETE ON TECNICO.INCIDENCIAS FROM USER2;

-- COMPRUEBO QUE USER2 YA NO TIENE EL PRIVILEGIO DELETE

SELECT * FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'USER2';

-- CON EL USUARIO 'TECNICO' CONCEDO A 'USER2' LA POSIBILIDAD DE ASIGNAR
-- PERMISO DE SELECT A OTROS USUARIOS SOBRE LA TABLA INCIDENCIAS

GRANT SELECT ON TECNICO.INCIDENCIAS TO USER2
WITH GRANT OPTION;

-- COMPRUEBO LA MODIFICACION SOBRE USER2

SELECT * FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'USER2';

-- CREO ROL LLAMADO 'ROLINCIDENCIAS' CON CARACTERISTICAS DE:
-- INICIAR SESION, LEER Y MODIFICAR LA TABLA INCIDENCIAS
-- NO PUDIENDO BORRAR NI AÑADIR

CREATE ROLE ROLINCIDENCIAS;

-- COMPRUEBO QUE EL ROL ESTA CREADO
SELECT ROLE FROM DBA_ROLES
WHERE ROLE = 'ROLINCIDENCIAS';

-- ASIGNO AL ROL INCIDENCIAS LAS CARACTERISTICAS DE:
-- INICIAR SESION, LEER Y MODIFICAR LA TABLA INCIDENCAS

GRANT CREATE SESSION TO ROLINCIDENCIAS;
GRANT SELECT, UPDATE ON TECNICO.INCIDENCIAS TO ROLINCIDENCIAS;

-- COMPRUEBO LOS PRIVILEGIOS DEL ROL INCIDENCIAS

SELECT PRIVILEGE, TABLE_NAME 
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'ROLINCIDENCIAS';

SELECT * FROM ROLE_SYS_PRIVS
WHERE ROLE = 'ROLINCIDENCIAS';

-- CREO EL USUARIO 'USER3' CON PASSWORD “SYSTEM1234” Y LE ASIGNO EL 
-- ROL INCIDENCIAS

CREATE USER USER3
IDENTIFIED BY "SYSTEM1234"
DEFAULT TABLESPACE EMPRESA
QUOTA UNLIMITED ON EMPRESA;
GRANT CREATE SESSION TO USER3;

-- ASIGNO EL ROL INCIDENCAS AL 'USER3'

GRANT ROLINCIDENCIAS TO USER3;

-- COMPRUEBO EL ROL DE 'USER3' 

SELECT GRANTEE, GRANTED_ROLE 
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'USER3'; 

-- COMPRUEBO LOS PERMISOS DE 'USER3'

SELECT * FROM DBA_TAB_PRIVS WHERE OWNER = 'USER3'; -- NO TIENE NINGUNO PORQUE TIENE UN ROL ASIGNADO

-- COMPRUEBO LOS PRIVILEGIOS DE 'USER3'

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE IN ('ROLINCIDENCIAS');

-- CREO UN PREFIL PARA USUARIOS LLAMADO 'PERFILUSUARIO' CON UN MAXIMO DE CONEXION
-- DE 1 HORA, 2 CONEXIONES SIMULTANEAS Y QUE OBLIGUE A CAMBIAR LA CANTRASEÑA
-- CADA 30 DIAS, LE ASIGNO ESTE PERFIL A 'USER3'

CREATE PROFILE PERFILUSUARIO LIMIT
CONNECT_TIME 60
SESSIONS_PER_USER 2
PASSWORD_LIFE_TIME 30;

-- ASIGNO EL 'PREFILUSUARIO' A 'USER3'

ALTER USER USER3 PROFILE PERFILUSUARIO;

-- COMPRUEBO LAS LIMITACIONES DEL PEFIL 'PERFILUSUARIO'

SELECT * FROM DBA_PROFILES
WHERE PROFILE = 'PERFILUSUARIO' AND LIMIT<> 'DEFAULT';

-- COMPRUEBO EL PERFIL ASIGNADO A 'USER3'

SELECT USERNAME, PROFILE FROM DBA_USERS
WHERE USERNAME = 'USER3';

-- CON EL USUARIO SYSTEM BORRO TODOS LOS USUARIOS, PERFILES Y ROLES CREADOS
-- EN EL SISTEMA

-- COMIENZO BORRANDO LOS USUARIOS

DROP USER USER1 CASCADE;
DROP USER USER2 CASCADE;
DROP USER TECNICO CASCADE;
DROP USER USER3 CASCADE;

-- COMPRUEBO QUE YA NO ESTAN EN EL SISTEMA

SELECT USERNAME FROM DBA_USERS
WHERE USERNAME = 'TECNICO' OR
      USERNAME = 'USER1' OR
      USERNAME = 'USER2' OR 
      USERNAME = 'USER3';

-- BORRO LOS PERFILES CREADOS;

DROP PROFILE PERFILUSUARIO CASCADE;

-- COMPRUEBO QUE ESTA BORRADO

SELECT PROFILE FROM DBA_PROFILES
WHERE PROFILE = 'PERFILUSUARIO';

-- BORRO LOS ROLES CREADOS

DROP ROLE ROLINCIDENCIAS;

-- COMPRUEBO QUE EL ROL INCIDENCIAS ESTA ELIMINADO DEL SISTEMA

SELECT ROLE FROM DBA_ROLES 
WHERE ROLE = 'ROLINCIDENCIAS';
